Repository panther-labs/panther_analysis_tool, pull requests merged in 2020-09, with the labels that each got.

#43 Lindseyw test dedup title
  panther_analysis_tool/main.py
  tests/fixtures/example_rule.py
  tests/fixtures/example_rule_missing_field.yml
  tests/fixtures/valid_analysis/rules/example_rule.yml
  tests/unit/panther_analysis_tool/test_main.py
Labels: team:security engineering

#44 Allowing packaging of just globals
  .github/CODEOWNERS
  panther_analysis_tool/main.py
  requirements-top-level.txt
  requirements.txt
  setup.py
Labels: enhancement, team:security engineering

#45 #37 - Display Name Validation
  panther_analysis_tool/schemas.py
  tests/fixtures/example_policy_invalid_characters.py
  tests/fixtures/example_policy_invalid_characters.yml
  tests/unit/panther_analysis_tool/test_main.py
Labels: bug, team:security engineering
